### ISSUE TITLE
Feature request: Color management identifiers

### ISSUE THREAD

**Issue by zerodean** [jeinselenVF/VF-BlenderAutosaveRender#11]
I love this addon. It would be great if it included color management identifiers (ie "View Transform") in the list of options. I specifically do render tests comparing Filmic and AGX and it would be nice if I was able to have that noted in filenames for when I check back on a render several months later. 

Additionally, being able to identify the "Look" (ie. High contrast, low contrast...) would also be amazing.

Example:

--{viewtransform}--{look}--

--AgX--HighContrast--
--Filmic--BaseContrast--

Thank you for your consideration.

**Comment by jeinselen** [comment]
Glad you like the addon @zerodean, and I agree! Those would be excellent additions, perhaps along with exposure and gamma values. Working on it now.

**Comment by zerodean** [comment]
Thank you @jeinselen. Love the additions. Please note that {space}--{look} for AGX High Contrast returns: 
"AgX--AgX-HighContrast" (note AgX redundancy) whereas Filmic High Contrast returns
"Filmic--HighContrast"

Ignore if intentional.

**Comment by jeinselen** [comment]
Thanks for reporting @zerodean!

I'd been primarily working in 3.6.x and had completely missed this. Looks like "AgX - " and "False Color - " are added to look titles when those respective colour spaces are used. I'm now filtering out both of those prepended strings, along with the spaces and periods in the device profile titles.

The changes are available now in version 2.8.1 when downloading from the GitHub source, but if I have time this week I hope to actually get an "official" release posted.
