### ISSUE TITLE
view layer variable

### ISSUE THREAD

**Issue by Bassssssss** [jeinselenVF/VF-BlenderAutosaveRender#9]
Hi would it be possible to add an view layer variable?

**Comment by jeinselen** [comment]
@Bassssssss Sure! `{viewlayer}` is now available in the latest commit: [VF_autosaveRender.py](https://raw.githubusercontent.com/jeinselenVF/VF-BlenderAutoSaveRender/main/VF_autosaveRender.py).

Same limitations apply as with the `{scene}` variable. It's the current _active_ view layer and does not necessarily reflect what's being rendered in the Compositor.

**Comment by Bassssssss** [comment]
clear and thank you!
